MeasureAuthoringTool/cql-antlr-parser

.github/workflows/gitleaks.yml

add gitleaks action to the repo

add gitleaks action

---

src/CqlAntlr.ts
src/CustomErrorListener.ts
test/CqlAntlr.test.ts
test/testCql.ts

MAT-3289 Ensure Antlr Error Messages Implemented from Antlr Parser

MAT-3289 Antlr Error check immplementation

---

.eslintrc.js
package-lock.json
package.json

update dependency versions, update eslint config; ref #MAT-3730
update package version to 0.0.12

Release 0.0.12

---

package-lock.json
package.json

changes to package.json: update version number, move to madie org, set publish access to public; ref #MAT-3730

Release 0.1.0

---

package-lock.json
package.json

Release v0.1.1

---

package.json
src/CqlAntlr.ts
src/CqlIdentifierCreator.ts
src/CustomErrorListener.ts
test/CqlAntlr.test.ts

- Disable non-grammar rules Report grammar error positions relative to line position instead of absolute character count
- Bump package version
- Codacy fix

Report Grammar Errors Relative to Line Position and Disable non-Grammar Error Checking

---

README.md

Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-0000)
*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

slack: Adding information about grammar files to README

---

package-lock.json
package.json
src/CqlAntlr.ts
src/CqlAntlrListener.ts
src/CqlRetrieveCreator.ts
src/dto/CqlResult.ts
src/dto/CqlRetrieve.ts
test/CqlAntlr.test.ts
test/testCql.ts

Jira Ticket: [MAT-5567](https://jira.cms.gov/browse/MAT-5567)
*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

MAT-5567 get all the retrieves

---

.eslintrc.js
.github/pull_request_template.md
.github/workflows/gitleaks.yml
README.md
jest.config.js
package.json
src/AntlrUtils.ts
src/CqlAntlr.ts
src/CqlAntlrListener.ts
src/CqlCodeCreator.ts
src/CqlCodeValueSystemCreator.ts
src/CqlContextCreator.ts
src/CqlErrorCreator.ts
src/CqlExpressionDefinitionCreator.ts
src/CqlExpressionVisitor.ts
src/CqlIncludeCreator.ts
src/CqlParameterCreator.ts
src/CqlRetrieveCreator.ts
src/CqlVersionCreator.ts
src/CreatorBase.ts
src/dto/CqlContext.ts
src/dto/CqlResult.ts
src/util/CqlFinder.ts
test/CqlAntlr.test.ts
test/CqlExpressionVisitor.test.ts
test/CqlFinder.test.ts
test/testCql.ts

Jira Ticket: [MAT-4844](https://jira.cms.gov/browse/MAT-4844)
*  Code is maintainable and reusable, reuses existing code and infrastructure where appropriate, and accomplishes the task’s purpose
*  The tests appropriately test the new code, including edge cases
*  If you have any concerns they are brought up either to the developer assigned, security engineer, or leads

Mat 4844 recognizing definitions sans quotes

---

package-lock.json

Jira Ticket: [MAT-4844](https://jira.cms.gov/browse/MAT-4844)

MAT-4844: Audit Fix

---

package-lock.json

Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-0000)

Release 1.0.3

---

package.json
src/AntlrUtils.ts
src/CqlAntlrListener.ts
src/CqlExpressionDefinitionCreator.ts
src/CreatorBase.ts
test/CqlAntlr.test.ts
test/testCql.ts

Jira Ticket: [MAT-4844](https://jira.cms.gov/browse/MAT-4844)

Mat 4844 fixing incorrect definition results

---

package-lock.json
package.json
src/AntlrUtils.ts
src/CqlAntlrListener.ts
src/CqlExpressionDefinitionCreator.ts
src/CreatorBase.ts
test/CqlAntlr.test.ts
test/testCql.ts

Jira Ticket: [MAT-4844](https://jira.cms.gov/browse/MAT-4844)

Release 1.0.4

---

package-lock.json
package.json
src/CqlAntlr.ts
src/CqlAntlrListener.ts
src/dto/CqlExpressionDefinition.ts
test/CqlAntlr.test.ts
test/commentTest.ts
test/testCql.ts

Jira Ticket: [MAT-7784](https://jira.cms.gov/browse/MAT-7784)

MAT-7784: Associate comments and inline comments with cql definitions

---

package-lock.json
package.json
src/CqlAntlr.ts
src/CqlAntlrListener.ts
src/dto/CqlResult.ts
test/CqlAntlr.test.ts
test/testCql.ts

Jira Ticket: [MAT-7652](https://jira.cms.gov/browse/MAT-7652)

MAT-7652 parse multiple using statements

---

package-lock.json
package.json
src/AntlrUtils.ts
src/CqlAntlr.ts
src/CqlAntlrListener.ts
src/dto/CqlResult.ts
test/CqlAntlr.test.ts
test/testCql.ts

Jira Ticket: [MAT-7652](https://jira.cms.gov/browse/MAT-7652)

Release 1.0.7

---

package-lock.json
package.json

Jira Ticket: [MAT-7784](https://jira.cms.gov/browse/MAT-7784)

Release 1.0.8

---

package-lock.json
package.json
src/AntlrUtils.ts
test/CqlAntlr.test.ts
test/CqlExpressionVisitor.test.ts
test/testCql.ts

Jira Ticket: [MAT-8079](https://jira.cms.gov/browse/MAT-8079)
separating multiple single comments with new line instead of  spaces

MAT-8079 separating multiple single comments with new line instead of spaces

---

package-lock.json
package.json
src/AntlrUtils.ts
test/CqlAntlr.test.ts
test/CqlExpressionVisitor.test.ts
test/testCql.ts

Jira Ticket: [MAT-8079](https://jira.cms.gov/browse/MAT-8079)
seperating multiple single comments with next line

Mat 8079/seperating multiple single comments with next line

---

package-lock.json
package.json

Jira Ticket: [MAT-8049](https://jira.cms.gov/browse/MAT-8049)

Release 1.0.13

---

.github/workflows/npm-publish.yml
package-lock.json
package.json

…ation
Jira Ticket: [MAT-0000](https://jira.cms.gov/browse/MAT-0000)

Release 1.0.14
